version: '2'
services:
  # postgres:
  #   image: postgres:11-alpine
  #   environment:
  #     POSTGRES_USER: prisma
  #     POSTGRES_PASSWORD: prisma
  #     ports:
  #       - 5432:5432
  #   volumes:
  #     - postgres:/var/lib/postgresql/data
  mongodb:
    image: mongo
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db

volumes:
  # postgres:
  mongodb:
