version: '3.5'
services:
  postgres:
    container_name: ts_microservice_postgres
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
  mongodb:
    container_name: ts_microservice_mongodb
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongodb:/data/db

  redis:
    container_name: ts_microservice_redis
    image: redis
    ports:
      - '6379:6379'

  zookeeper:
    container_name: ts_microservice_zookeeper
    image: wurstmeister/zookeeper
    ports:
      - '2181:2181'

  kafka:
    container_name: ts_microservice_kafka
    image: wurstmeister/kafka
    ports:
      - '9092:9092'
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # HOSTNAME_COMMAND: "docker info | grep ^Name: | cut -d' ' -f 2"
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE

    links:
      - zookeeper
    depends_on:
      - zookeeper
    # volumes:
    #   - /var/run/docker.sock:/var/run/docker.sock

  webview:
    container_name: ts_microservice_webview
    image: sourcelaborg/kafka-webview
    expose:
      - 8080
    ports:
      - '3331:8080'
    links:
      - kafka
volumes:
  postgres:
  mongodb:

networks:
  default:
    name: ts_microservice
