apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: ts-microservice-demo
  labels:
    app: mongodb
spec:
  ports:
  - port: 27017
    name: mongo
  selector:
    app: mongodb
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongodb
  namespace: ts-microservice-demo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb 
        image: mongo
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 27017
---
