apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: ts-microservice-demo
  labels:
    app: kafka
spec:
  type: LoadBalancer
  selector:
    app: kafka
  ports:
    - name: tcp
      protocol: TCP
      port: 9092
      targetPort: 9092
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kafka
  namespace: ts-microservice-demo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka 
          image: wurstmeister/kafka
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9092
            - containerPort: 9093
          env:
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper:2181"
            - name: KAFKA_PORT
              value: "9092"
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: "kafka"