apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: ts-microservice-demo
  labels:
    app: mongodb
spec:
  type: LoadBalancer
  selector:
    app: mongodb
  ports:
    - name: tcp
      port: 27017
      targetPort: 27017
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongodb
  namespace: ts-microservice-demo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb 
          image: mongo
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: /data/db
              name: mongodb
      volumes:
      - name: mongodb
        hostPath:
          path: /data/mongodb
          type: DirectoryOrCreate