apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: ts-microservice-demo
  labels:
    app: postgres
spec:
  type: LoadBalancer
  selector:
    app: postgres
  ports:
    - name: tcp
      protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres
  namespace: ts-microservice-demo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres 
          image: postgres:11-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres
          env:
            - name: POSTGRES_USER
              value: "root"
            - name: POSTGRES_PASSWORD
              value: "123456"
      volumes:
      - name: postgres
        hostPath:
          path: /data/postgres
          type: DirectoryOrCreate