apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: ts-microservice-demo
  labels:
    app: redis
spec:
  type: LoadBalancer
  selector:
    app: redis
  ports:
    - name: tcp
      port: 6379
      targetPort: 6379
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis
  namespace: ts-microservice-demo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis 
          image: redis
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
